version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: ./
    volumes:
      - ./php/src:/var/www/html/
      - ./php/src/upload:/var/www/html/upload
    ports:
      - 80:80
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: blog
      MYSQL_USER:  MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9906:3306"
